# Generated by Django 4.2.7 on 2023-11-22 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(default='', verbose_name='متن')),
                ('send_datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال ایمیل')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
