# Generated by Django 4.2.7 on 2023-11-22 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useremail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='message',
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='user',
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(default='', verbose_name='متن')),
                ('user', models.ManyToManyField(through='accounts.UserEmail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
        migrations.AddField(
            model_name='useremail',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email2', to='accounts.email', verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
